from typing import Protocol, TypeVar

T = TypeVar("T")
U = TypeVar("U")


class PipeConnectionI[T, U](Protocol):
    def send(self, obj: T): ...
    def recv(self) -> U: ...
    def poll(self, timeout: float | None = 0) -> bool: ...
    def close(self): ...
